language: java
jdk: openjdk8
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: aY1B62slOgL6c+eVLsnV+41LlzU0NsqbLjOgIcE3yV6BB9MkEbegtPrLPY27Tsi6nhy//gpyq73UghUGSZBhSuQ/RTwAtHTbY0KydcT+Koz3boQWLGTSSphMqZuGSlP2HouPL8zJQsuftRn/xn7Sprq+pNLXsSazDaoJy5Ivs2SDX2yIPxTtnNohWPsX5IrMl97QeceWRzHA6bZ+dNH9aN3RVVJf7OMcJ/dpbWIWO6NE8vBBnsP/VoYXwV/GZd8q1OQrxha71VsJsSZcIjtblfnigG2LMorcju7G84aiQZuglhpYMTPMMLFIrjUfw59rCAVa4VuGKH6Z8SdEPR/DxBW43ye/EiLkf1sUkZOzK4ja/cI+5GxbuXBSceA6p9+ixLSq0mWvVnr54+JaRZP7hgSG60szku+aTHfz0abc9lF09TAIXeNdzEBlnJ6/LD6QO66sRsmBdVdXGAIyYA7D/IGhmNBttSymQB5Ut1S1nqDux2zPtBhhtTPWGnJABG89YWJZ6rLMNJRO4wt7qOzK4lZsrHxCTQf+DVwIIEp5sn0yCNVhsz2i8whD3qNa3D2lFAvpupvMUYl2jxUqA4n1X0qdwhUHxcmK0OipQ/9eR/VHpISxhS5sPFdXkgvl9q2wRwiIdx2quOnU/ydAbrYoQex0JvjD3IlQeXRIgVjQMYI=
  on:
    branch: work
